=== Climber-Hub/climberhub-core/schemas/route/schema.json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"definitions": {
    "Rules": {
        "type": "object",
        "properties": {
        "sitstart"        : {"type": "boolean"},
        "modules_allowed" : {"type": "boolean"},
        "edges_allowed"   : {"type": "boolean"}
        },
        "required": ["sitstart", "modules_allowed", "edges_allowed"],
        "additionalProperties": false
    }
},
"type": "object",
"properties": {
    "id"           : {"type": "string"},
    "place_id"     : {"type": "string"},
    "name"         : {"type": "string"},
    "description"  : {"type": "string"},
    "grade"        : {"type": "string"},
    "color"        : {"type": "string"},
    "sector"       : {"type": "string"},
    "opening_date" : {"type": "string", "format": "date"},
    "closing_date" : {"type": ["string", "null"], "format": "date"},
    "rules"        : {"$ref": "#/definitions/Rules"},
    "tags"         : {"type": "array", "items": {"type": "string"}},
    "properties"   : {"type": "object", "additionalProperties": {"type": "string"}}
},
"required": ["id", "place_id", "name", "description", "grade", "color", "sector", "opening_date", "rules", "tags", "properties"]
}

=== Climber-Hub/climberhub-core/schemas/route/example.json
{
  "id"           : "1",
  "place_id"     : "1",
  "name"         : "Rocky Road",
  "description"  : "A challenging climb with lots of twists and turns.",
  "grade"        : "5c",
  "color"        : "red",
  "sector"       : "North Wall",
  "opening_date" : "2021-01-01",
  "closing_date" : null,
  "rules"        : {
    "sitstart"        : true,
    "modules_allowed" : true,
    "edges_allowed"   : false
  },
  "tags": ["challenging", "twisty"],
  "properties": {
    "height": "20m",
    "rating": "5 stars"
  }
}
